name: Respawnglitchfix
version: '${project.version}'
main: me.ayaan.respawnglitchfix.Main
api-version: 1.17
authors: [ Compgeek28, Ayaan ]
description: Simple solution to the respawn glitch in EARTHITOC
website: earthitoc.org
commands:
  instantrespawn:
    description: Reload the config
permissions:
  instantrespawn.command:
    default: false
  instantrespawn.respawn:
    default: false
  instantrespawn.reload:
    default: false